const menu = [
    {
      id: 1,
      title: 'Bánh Kếp',
      category: 'Bữa Sáng',
      price: 15.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fpancakes.webp?alt=media&token=72a7e933-0e60-49fa-b267-be768784f517',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Cơm Trộn',
      category: 'Bữa Trưa',
      price: 13.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fcon-tron.webp?alt=media&token=4100161f-7700-44fb-90bd-e86091fcd22b',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Kem Tươi',
      category: 'Tráng Miệng',
      price: 6.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fice%20cream.webp?alt=media&token=75e688ac-995d-404a-a1ad-74884c6b660b',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Phở',
      category: 'Bữa Sáng',
      price: 20.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fpho.webp?alt=media&token=982a2920-1cd9-41fc-ba6f-7cd2833a8d51',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Mỳ Trộn',
      category: 'Bữa Trưa',
      price: 22.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fmy-tron.webp?alt=media&token=3358d38b-0d72-432b-ae58-3063f5ccb893',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Sữa Chua',
      category: 'Tráng Miệng',
      price: 18.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fsua-chua.webp?alt=media&token=bb106b0b-c96a-4f52-a778-eb4645ca7845',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Bánh Sừng Bò',
      category: 'Bữa Sáng',
      price: 8.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fbanh-sung-bo.webp?alt=media&token=42bbdf9a-5c10-4d78-85d7-09db5db89522',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Pizza',
      category: 'Bữa Trưa',
      price: 12.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fpizza.webp?alt=media&token=68c22422-8fcb-4058-b38a-078bcf9a4e27',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Nước Ép Dưa Hấu',
      category: 'Tráng Miệng',
      price: 16.99,
      img: 'https://firebasestorage.googleapis.com/v0/b/menu-a0a06.appspot.com/o/images%2Fnuoc-dua-hau.webp?alt=media&token=00f8b2b4-7cb9-442e-bda6-39c90cef97b2',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;